### ISSUE TITLE
Return SOA record when not exist PTR record

### ISSUE THREAD

**Issue by taketo1113** [ankane/reversed#5]
### Steps to reproduce
It returns a value of SOA record when not exist PTR record.

```ruby
Reversed.lookup('128.66.0.1', nameservers: ["8.8.8.8"])
=> "z.arin.net"
```

### Expected behavior
It returns `nil` when no existing PTR record.

### Actual behavior
- env
  - ruby: 3.1.3
  - reversed: v0.4.0

#### Examples
The code below is an example result of `resolver.answer` and `resolver.authority`.

It would be nice to fix returning only `resolver.answer` (excluding `resolver.authority`).

ref. https://github.com/ankane/reversed/blob/master/lib/reversed.rb#L28

````ruby
ip = IPAddr.new('128.66.0.1')
#=> #<IPAddr: IPv4:128.66.0.1/255.255.255.255>
resolver = Net::DNS::Resolver.new().search(ip.reverse, Net::DNS::PTR)
#=> 
#;; Answer received from 10.128.128.128:53 (95 bytes)                                              
#...                                                                                               

resolver.answer.first
=> nil

resolver.authority.first
=> 128.in-addr.arpa.       10800   IN      SOA     z.arin.net. dns-ops.arin.net. 2017035003 1800 900 691200 10800
````

#### dig command
```
$ dig @8.8.8.8 -x 128.66.0.1

; <<>> DiG 9.10.6 <<>> @8.8.8.8 -x 128.66.0.1
;; QUESTION SECTION:
;1.0.66.128.in-addr.arpa.	IN	PTR

;; AUTHORITY SECTION:
128.in-addr.arpa.	1644	IN	SOA	z.arin.net. dns-ops.arin.net. 2017035003 1800 900 691200 10800
```

**Comment by ankane** [comment]
Hey @taketo1113, thanks for the suggestion. Added a `fallback` option in the commit above that can be used to disable the SOA fallback.

```ruby
Reversed.lookup(ip, fallback: false)
```

**Comment by taketo1113** [comment]
Thanks.
I comfirmed to add a fallback option.

```ruby
Reversed.lookup('128.66.0.1', nameservers: ["8.8.8.8"], fallbac
k: false)
=> nil
```
