### ISSUE TITLE
uninitialized constant Net::DNS::Resolver::TimeoutError

### ISSUE THREAD

**Issue by ujinius** [ankane/reversed#6]
when timeout is happening I got:

`NameError (uninitialized constant Net::DNS::Resolver::TimeoutError)`

It can be reproduced simply:

```
irb(main):002:0> Reversed.lookup('8.8.4.4', timeout: 0.0001)
Traceback (most recent call last):
        1: from (irb):2
NameError (uninitialized constant Net::DNS::Resolver::TimeoutError)
irb(main):003:0> 
```

**Comment by ankane** [comment]
Hey @ujinius, thanks for reporting! Unfortunately, it's an issue with the `net-dns` gem (https://github.com/bluemonk/net-dns/issues/82), but since it hasn't been updated in a while, I think it's fine to patch it.

**Comment by ujinius** [comment]
Thanks a lot, @ankane

**Comment by ujinius** [comment]
@ankane could you please give a hint when you plan to release 0.4.2 (which includes this PR)? We are about in dependency of the fix. Thank you!

**Comment by ankane** [comment]
Just pushed a new release.
